### PR TITLE
Mogulx operates/issue132

### PR DESCRIPTION
**Pull request by mogulx-operates**

### CODE REVIEW

**Comment by mogulx-operates** [comment]
- adds nodejs hello world guide

**Comment by mogulx-operates** [comment]
fixing style

**Comment by mogulx-operates** [comment]
Screen Shot 2023-03-18 at 12 31 41 PM
Screen Shot 2023-03-18 at 12 31 51 PM
Screen Shot 2023-03-18 at 12 32 04 PM

**Review by twilson63 — APPROVED** [review]
Looks like you are adding a trailing comma to config file, but otherwise, LGTM

**Comment by mogulx-operates** [comment]
I cannot merge, but let me know if you want me to fix the formatting.  I was thinking I would make another issue for a format script. Would that be useful, to be able to run it just before pushing or something?

**Comment by twilson63** [comment]
@mogulx-operates 

Added formating, you should be able to rebase your branch from upstream and the run `yarn fmt`

**Pull request merged**
